import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const roots: string[] = [];
const repoRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const syncVersionScript = join(repoRoot, "scripts", "sync-version.mjs");

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function tempRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "m4a-version-sync-"));
  roots.push(root);
  return root;
}

function writeVersionFixture(root: string, versions: { packageJson: string; cargoToml: string; cargoLock: string }): void {
  mkdirSync(join(root, "crates", "mason4agents"), { recursive: true });
  writeFileSync(join(root, "package.json"), JSON.stringify({
    name: "mason4agents",
    version: versions.packageJson,
  }, null, 2));
  writeFileSync(join(root, "crates", "mason4agents", "Cargo.toml"), [
    "[package]",
    "name = \"mason4agents\"",
    `version = \"${versions.cargoToml}\"`,
    "edition.workspace = true",
    "",
    "[dependencies]",
    "serde = \"1.0\"",
    "",
  ].join("\n"));
  writeFileSync(join(root, "Cargo.lock"), [
    "# This file is automatically @generated by Cargo.",
    "version = 4",
    "",
    "[[package]]",
    "name = \"dependency\"",
    "version = \"1.0.0\"",
    "",
    "[[package]]",
    "name = \"mason4agents\"",
    `version = \"${versions.cargoLock}\"`,
    "dependencies = [",
    " \"dependency\",",
    "]",
    "",
  ].join("\n"));
}

function runSyncVersion(root: string, ...args: string[]): ReturnType<typeof spawnSync> {
  return spawnSync(process.execPath, [syncVersionScript, "--root", root, ...args], {
    cwd: root,
    encoding: "utf8",
  });
}

describe("version sync script", () => {
  test("check fails when Cargo files drift from package.json", () => {
    const root = tempRoot();
    writeVersionFixture(root, { packageJson: "1.2.3", cargoToml: "1.2.2", cargoLock: "1.2.2" });

    const result = runSyncVersion(root, "--check");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("Version files are out of sync with package.json 1.2.3");
    expect(result.stderr).toContain("crates/mason4agents/Cargo.toml");
    expect(result.stderr).toContain("Cargo.lock");
  });

  test("sync updates Cargo files from package.json", () => {
    const root = tempRoot();
    writeVersionFixture(root, { packageJson: "1.2.3-beta.1+build.5", cargoToml: "1.2.2", cargoLock: "1.2.2" });

    const result = runSyncVersion(root);

    expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0);
    expect(readFileSync(join(root, "crates", "mason4agents", "Cargo.toml"), "utf8")).toContain("version = \"1.2.3-beta.1+build.5\"");
    expect(readFileSync(join(root, "Cargo.lock"), "utf8")).toContain("name = \"mason4agents\"\nversion = \"1.2.3-beta.1+build.5\"");
  });

  test("check passes when versions match", () => {
    const root = tempRoot();
    writeVersionFixture(root, { packageJson: "1.2.3", cargoToml: "1.2.3", cargoLock: "1.2.3" });

    const result = runSyncVersion(root, "--check");

    expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0);
    expect(result.stdout).toContain("Version files are in sync: 1.2.3");
  });
});
